Auto-commit: 0 added, 1 modified, 0 deleted

diff --git a/config/shellz/run-wayfire b/config/shellz/run-wayfire
--- a/config/shellz/run-wayfire
+++ b/config/shellz/run-wayfire
@@ -14,6 +14,33 @@ export XDG_SESSION_DESKTOP=wayfire
 export XDG_CURRENT_DESKTOP=wayfire
 export XDG_CURRENT_SESSION=wayfire
 
+# --- // EXPLICITY_SET_WAYFIRE_DIRS:
+XDG_DATA_DIRS=$XDG_DATA_DIRS
+
+if [ -d "XDG_DATA_HOME" ]; then
+    DEFAULT_LOG_DIR=$XDG_DATA_HOME/wayfire
+else
+    DFAULT_LOG_DIR=$HOME/.local/share/wayfire
+fi
+
+# --- // SETUP_LOGGING:
+mkdir -p $DEFAULT_LOG_DIR
+if [ $? != 0 ]; then
+    echo "Could not create log directory $DEFAULT_LOG_DIR"
+    echo "Using stdout as log"
+    wayfire "$@"
+ elif [ ! -z "$WAYLAND_DISPLAY" ] || [ ! -z "$DISPLAY" ]; then
+     echo "RUnning nested, using stdout as log"
+     wayfire "$@"
+ else
+     LOG_FILE=$DEFAULT_LOG_DIR/wayfire.log
+     if [ -f $LOG_FILE ]; then
+         cp $LOG_FILE $LOG_FILE.old
+     fi
+     echo "Using log file: $LOG_FILE"
+     wayfire "@" &> $LOG_FILE
+ fi
+ 
 # --- // GTK_VARIABLES:
 export TDESKTOP_DISABLE_GTK_INTEGRATION=1
 export CLUTTER_BACKEND=wayland,x11
