Auto-commit: 0 added, 4 modified, 0 deleted

diff --git a/config/shellz/run-wayfire b/config/shellz/run-wayfire
--- a/config/shellz/run-wayfire
+++ b/config/shellz/run-wayfire
@@ -22,9 +22,13 @@ export BEMENU_BACKEND=wayland
 
 export MOZ_ENABLE_WAYLAND=1
 export QT_QPA_PLATFORMTHEME=qt5ct
+export AWT_TOOLKIT="MTookit wmname LG3D"
+export _JAVA_AWT_WM_NONREPARENTING=1
+export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel ${_JAVA_OPTIONS}"
+
 export QT_AUTO_SCREEN_SCALE_FACTOR=1
-export QT_QPA_PLATFORM=wayland-egl #error with apps xcb
-#export QT_WAYLAND_FORCE_DPI=physical #uncomment this to use monitor's DPI
+export QT_QPA_PLATFORM=wayland-egl  # Avoid using xcb for Wayland sessions
+export QT_WAYLAND_FORCE_DPI=physical # Use monitor's DPI
 export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
 
 
@@ -34,11 +38,8 @@ export ELM_ENGINE=wayland_egl
 export ELM_ACCEL=opengl
 #export ELM_SCALE=1
 
-#export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -#Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -#Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel ${_JAVA_OPTIONS}"
-
 
 export SDL_VIDEODRIVER=wayland
-export _JAVA_AWT_WM_NONREPARENTING=1
 export SAL_USE_VCLPLUGIN=gtk3
 
 export GDK_BACKEND=wayland,x11
@@ -48,7 +49,10 @@ export WINIT_UNIX_BACKEND=wayland
 export ELECTRON_OZONE_PLATFORM_HINT=wayland
 
 # --- // SYSTEMD_DBUS:
-eval "$(dbus-launch --sh-syntax)"
+if ! eval "$(dbus-launch --sh-syntax)"; then
+    echo "Failed to launch D-Bus session bus."
+    exit 1
+fi
 export DBUS_SESSION_BUS_ADDRESS
 export DBUS_SESSION_BUS_PID
 #xhost + </dev/null &>/dev/null &
@@ -56,7 +60,7 @@ export DBUS_SESSION_BUS_PID
 #xhost +SI:localuser:root
 
 # --- // EXEC_WAYFIRE:
-sleep 0.5;
+sleep 0.5
 
 if ! command -v wayfire &> /dev/null; then
     echo "Wayfire could not be found, please install it."
