Auto-commit: 0 added, 2 modified, 0 deleted

diff --git a/config/shellz/zenvironment b/config/shellz/zenvironment
--- a/config/shellz/zenvironment
+++ b/config/shellz/zenvironment
@@ -12,7 +12,7 @@ all_dirs=(
     "$HOME/.config/yarn/global/node_modules/.bin"
     "$HOME/.local/share/go/"
     "/usr/local/go/bin"
-#    "${JAVA_HOME:-/usr/lib/jvm/default/bin}"  # Use JAVA_HOME if set, else default
+    "${JAVA_HOME:-/usr/lib/jvm/default/bin}"  # Use JAVA_HOME if set, else default
     "$HOME/.rvm/bin"
     "$HOME/.virtualenvs"
     "$HOME/.poetry/bin"
@@ -35,6 +35,7 @@ for dir in "${all_dirs[@]}"; do
 done
 export PATH
 
+# Ensure unique path elements
 typeset -U path PATH cdpath CDPATH fpath FPATH manpath MANPATH
 
 unsetopt PROMPT_SP 2>/dev/null
@@ -44,11 +45,19 @@ export MICRO_TRUECOLOR=1
 export EDITOR="/usr/bin/micro"
 export TERMINAL="alacritty"
 export TERMINAL_PROG="alacritty"
-export BROWSER="brave"
+export BROWSER="brave-browser-beta"
 
-# --- // XDG_SETUP:
-export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
-mkdir -p "$XDG_RUNTIME_DIR"
+# --- // XDG_RUNTIME_DIR_SETUP:
+if [ -z "$XDG_RUNTIME_DIR" ]; then
+    export XDG_RUNTIME_DIR="/run/user/$(id -u)"
+fi
+
+if [ ! -d "$XDG_RUNTIME_DIR" ]; then
+    mkdir -p "$XDG_RUNTIME_DIR"
+fi
+# --- // XDG_DATA_DIRS_SETUP:
+[ -z "$XDG_DATA_DIRS" ] && export XDG_DATA_DIRS="/usr/local/share:/usr/share"
+
 export XDG_CONFIG_HOME="$HOME/.config"
 export XDG_DATA_HOME="$HOME/.local/share"
 export XDG_CACHE_HOME="$HOME/.cache"
@@ -68,6 +77,8 @@ export CARGO_HOME="$XDG_DATA_HOME/cargo"
 export GOPATH="$XDG_DATA_HOME/go"
 export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
 export POETRY_CACHE_DIR="$XDG_CACHE_HOME/poetry"
+export POETRY_HOME="$XDG_CONFIG_HOME/poetry"
+export POETRY_VIRTUALENVS_PATH="$XDG_DATA_HOME/poetry/virtualenvs"
 export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
 export PIP_DOWNLOAD_CACHE="$HOME/.pip/cache"
 export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
@@ -97,19 +108,16 @@ export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
 #zstyle ':completion:*' cache-path ~/.cache/zcache
 #autoload -U +X bashcompinit && bashcompinit  # Automatically load bash completion functions
 
+# Handle terminal mode keybindings
+typeset -g -A key
+
 # -------------------------------- // LIBRARY_AND_SECURITY //
-if [ -z "$LD_LIBRARY_PATH" ]; then
-    export LD_LIBRARY_PATH="$HOME/.local/lib"
-else
-    export LD_LIBRARY_PATH="$HOME/.local/lib:/usr/local/lib/python3.11/site-packages:/usr/lib:$LD_LIBRARY_PATH"
-fi
+[ -z "$LD_LIBRARY_PATH" ] && export LD_LIBRARY_PATH="$HOME/.local/lib" || export LD_LIBRARY_PATH="$HOME/.local/lib:/usr/local/lib/python3.11/site-packages:/usr/lib:$LD_LIBRARY_PATH"
 
 export GNUPGHOME="$HOME/.gnupg"
-if [ ! -d "$GNUPGHOME" ]; then
-    mkdir -p "$GNUPGHOME"
-fi
-
+mkdir -p "$GNUPGHOME"
 chmod 700 "$GNUPGHOME"
+
 export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
 export SUDO_ASKPASS="/usr/bin/pinentry-dmenu"
 # export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
@@ -118,17 +126,15 @@ export SUDO_ASKPASS="/usr/bin/pinentry-dmenu"
 #gpg-connect-agent reloadagent /bye >/dev/null
 #eval $(ssh-agent) && ssh-add 2&>/dev/null
 
+
 # ------------------------------------------------------- // PAGER //
 # Use Bat:
-#export MANPAGER="sh -c 'col -bx | bat -l man -p'"
+export MANPAGER="sh -c 'col -bx | bat -l man -p'"
 #export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --preview 'bat --style=numbers --color=always --line-range :500 {}'"
+
 case "${COLORTERM}" in
-    truecolor)
-        # Do not overwrite; already supports truecolor
-        ;;
-    *)
-        export COLORTERM="yes"
-        ;;
+    truecolor) ;;  # Already supports truecolor
+    *) export COLORTERM="yes" ;;
 esac
 
 export FZF_DEFAULT_OPTS="
@@ -157,134 +163,11 @@ export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
 export MOZ_USE_XINPUT2=1                  # Mozilla smooth scrolling/touchpads.
 export AWT_TOOLKIT="MToolkit wmname LG3D" # May have to install wmname
 
-# ------------------------------ // KEYBINDINGS_BASED_ON_EMACS //
-bindkey -e
 
-# [PageUp] - Up a line of history
-if [[ -n "${terminfo[kpp]}" ]]; then
-  bindkey -M emacs "${terminfo[kpp]}" up-line-or-history
-  bindkey -M viins "${terminfo[kpp]}" up-line-or-history
-  bindkey -M vicmd "${terminfo[kpp]}" up-line-or-history
-fi
-
-# [PageDown] - Down a line of history
-if [[ -n "${terminfo[knp]}" ]]; then
-  bindkey -M emacs "${terminfo[knp]}" down-line-or-history
-  bindkey -M viins "${terminfo[knp]}" down-line-or-history
-  bindkey -M vicmd "${terminfo[knp]}" down-line-or-history
-fi
-
-# Start typing + [Up-Arrow] - fuzzy find history forward
-if [[ -n "${terminfo[kcuu1]}" ]]; then
-  autoload -U up-line-or-beginning-search
-  zle -N up-line-or-beginning-search
-
-  bindkey -M emacs "${terminfo[kcuu1]}" up-line-or-beginning-search
-  bindkey -M viins "${terminfo[kcuu1]}" up-line-or-beginning-search
-  bindkey -M vicmd "${terminfo[kcuu1]}" up-line-or-beginning-search
-fi
-
-# Start typing + [Down-Arrow] - fuzzy find history backward
-if [[ -n "${terminfo[kcud1]}" ]]; then
-  autoload -U down-line-or-beginning-search
-  zle -N down-line-or-beginning-search
-
-  bindkey -M emacs "${terminfo[kcud1]}" down-line-or-beginning-search
-  bindkey -M viins "${terminfo[kcud1]}" down-line-or-beginning-search
-  bindkey -M vicmd "${terminfo[kcud1]}" down-line-or-beginning-search
-fi
-
-# [Home] - Go to beginning of line
-if [[ -n "${terminfo[khome]}" ]]; then
-  bindkey -M emacs "${terminfo[khome]}" beginning-of-line
-  bindkey -M viins "${terminfo[khome]}" beginning-of-line
-  bindkey -M vicmd "${terminfo[khome]}" beginning-of-line
-fi
-
-# [End] - Go to end of line
-if [[ -n "${terminfo[kend]}" ]]; then
-  bindkey -M emacs "${terminfo[kend]}" end-of-line
-  bindkey -M viins "${terminfo[kend]}" end-of-line
-  bindkey -M vicmd "${terminfo[kend]}" end-of-line
-fi
-
-# [Shift-Tab] - move through the completion menu backwards
-if [[ -n "${terminfo[kcbt]}" ]]; then
-  bindkey -M emacs "${terminfo[kcbt]}" reverse-menu-complete
-  bindkey -M viins "${terminfo[kcbt]}" reverse-menu-complete
-  bindkey -M vicmd "${terminfo[kcbt]}" reverse-menu-complete
-fi
-
-# [Backspace] - delete backward
-bindkey -M emacs '^?' backward-delete-char
-bindkey -M viins '^?' backward-delete-char
-bindkey -M vicmd '^?' backward-delete-char
-
-# [Delete] - delete forward
-if [[ -n "${terminfo[kdch1]}" ]]; then
-  bindkey -M emacs "${terminfo[kdch1]}" delete-char
-  bindkey -M viins "${terminfo[kdch1]}" delete-char
-  bindkey -M vicmd "${terminfo[kdch1]}" delete-char
-else
-  bindkey -M emacs "^[[3~" delete-char
-  bindkey -M viins "^[[3~" delete-char
-  bindkey -M vicmd "^[[3~" delete-char
-
-  bindkey -M emacs "^[3;5~" delete-char
-  bindkey -M viins "^[3;5~" delete-char
-  bindkey -M vicmd "^[3;5~" delete-char
-fi
-
-# Terminal modes key handling
-typeset -g -A key
-if (( ${+terminfo[smkx]} && ${+terminfo[rmkx]} )); then
-	autoload -Uz add-zle-hook-widget
-	function zle_application_mode_start { echoti smkx }
-	function zle_application_mode_stop { echoti rmkx }
-	add-zle-hook-widget -Uz zle-line-init zle_application_mode_start
-	add-zle-hook-widget -Uz zle-line-finish zle_application_mode_stop
-fi
-
-# Control Left - go back a word
-key[Control-Left]="${terminfo[kLFT5]}"
-if [[ -n "${key[Control-Left]}" ]]; then
-    bindkey -M emacs "${key[Control-Left]}" backward-word
-    bindkey -M viins "${key[Control-Left]}" backward-word
-    bindkey -M vicmd "${key[Control-Left]}" backward-word
-fi
-
-# Alt Left - go back a word
-key[Alt-Left]="${terminfo[kLFT3]}"
-if [[ -n "${key[Alt-Left]}" ]]; then
-    bindkey -M emacs "${key[Alt-Left]}" backward-word
-    bindkey -M viins "${key[Alt-Left]}" backward-word
-    bindkey -M vicmd "${key[Alt-Left]}" backward-word
-fi
-
-# Control Right - go forward a word
-key[Control-Right]="${terminfo[kRIT5]}"
-if [[ -n "${key[Control-Right]}" ]]; then
-    bindkey -M emacs "${key[Control-Right]}" forward-word
-    bindkey -M viins "${key[Control-Right]}" forward-word
-    bindkey -M vicmd "${key[Control-Right]}" forward-word
-fi
-
-# Alt Right - go forward a word
-key[Alt-Right]="${terminfo[kRIT3]}"
-if [[ -n "${key[Alt-Right]}" ]]; then
-    bindkey -M emacs "${key[Alt-Right]}" forward-word
-    bindkey -M viins "${key[Alt-Right]}" forward-word
-    bindkey -M vicmd "${key[Alt-Right]}" forward-word
-fi
-
-# --- // SPEEDUP_KEYS:
-if command -v xset &>/dev/null; then
-    xset r rate 300 50
-else
-    echo "xset command not found, skipping keyboard rate configuration."
-fi
-
+# ------------------------------------------------------------ // MISC //
+# --- // SPEEDUP KEYS:
+#command -v xset &>/dev/null && xset r rate 300 50 || echo "xset command not found, skipping keyboard rate configuration."
+xset r rate 300 50 
 
 # --- // LF_SHORTCUTS:
 [ ! -f "$XDG_CONFIG_HOME/shell/shortcutrc" ] && setsid -f shortcuts >/dev/null 2>&1
-
