updated 4ndr0cht and getkeys

diff --git a/home/andro/.local/bin/getkeys b/home/andro/.local/bin/getkeys
--- a/home/andro/.local/bin/getkeys
+++ b/home/andro/.local/bin/getkeys
@@ -1,88 +1,71 @@
 #!/bin/sh
 # Author: 4ndr0666
 # ================== // GETKEYS //
-## Description:
-#    Pulls txt files detailing keybinds and shortcuts for
-#    specfic programs
-## Usage:
-#    getkeys <list of keybinds>
+## Description: Pulls txt files detailing keybinds 
+#               and shortcuts for specfic programs
+## Usage: getkeys <list of keybinds>
 # ---------------------------------------------
 
-
-
-
-#### Force 24-bit color mode if not already set
+# Force 24bit
 case "${COLORTERM}" in
     truecolor | 24bit) ;;  # Already OK
      *) export COLORTERM="24bit" ;;  # Set to safe default
 esac
 
-#### Advanced or Plain Text Color Functions
-if command -v tput >/dev/null && [[ -t 1 ]]; then
+# Favorite color
+CYAN="\033[38;2;21;255;255m"
+NC="\033[0m"
+
+# Tput or fallback to ansi
+if command -v tput >/dev/null && [ -t 1 ]; then
    GLOW() { printf '%s\n' "$(tput setaf 6) $*$(tput sgr0)"; }
-
 else
-   GLOW() { printf '%s\n' "$*"; }
-
+   GLOW() { printf '%s\n' "${CYAN} $*${NC}"; }
 fi
   
-## Constants
-
+# Constants
 KEYS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/4ndr0666/getkeys"
 
-## Help
-
+# Help
 usage() {
-	echo "Available Keybindings:"
-	echo ""
-	ls "$KEYS_DIR" | sort | column
+	printf '%s\n\n' "Available Keybindings:"
+	find "$KEYS_DIR" | sort | column
 }
 
-## Validate
-
+# Validate
 if [ ! -d "$KEYS_DIR" ]; then
-	echo "Error: Keybindings directory '$KEYS_DIR' does not exist." >&2
+	printf '%s\n' "Error: Keybindings directory '$KEYS_DIR' does not exist." >&2
 	exit 1
 fi
 
-## Options
-
+# Options
 case "$1" in
 -h | --help)
 	usage
 	exit 0
 	;;
 -v | --version)
-	echo "getkeys version 1.1"
+	printf '%s\n' "getkeys version 1.1"
 	exit 0
 	;;
 esac
-
-## Validate
 
 if [ $# -lt 1 ]; then
 	usage
 	exit 1
 fi
 
-## For Loop Keybinds at "$HOME/.local/share/4ndr0666/getkeys"
-
+# For Loop Keybinds at "$HOME/.local/share/4ndr0666/getkeys"
 for program in "$@"; do
 	FILE="$KEYS_DIR/$program"
-	if [ -f "$FILE" ]; then
-		GLOW "============================"
-	        printf '     %s\n' "Commands for: $program"
-		GLOW "----------------------------"
-		if command -v bat >/dev/null 2>&1; then
-                    bat --language=sh "$FILE"
-		elif command -v cat >/dev/null 2>&1; then
-			cat "$FILE"
-		else
-			echo "Error: Neither 'bat' nor 'cat' is installed." >&2
+	if [ -f "$FILE" ]; then	
+#	    printf '  %s\n' "==> $program"
+#        printf '%s\n' "${CYAN} $*${NC}"; }
+		bat --style=snip --paging=always --language=sh "$FILE" || {
+			printf '%s' "Error: 'bat' not installed." >&2
 			exit 1
-		fi
-		echo "" # Add a newline for better readability
+		}
 	else
-		echo "Error: No keybinding file found for '$program'." >&2
+		printf '%s\n\n' "Error: No keybinding file found for '$program'." >&2
 	fi
 done
